service: roastly-api

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-domain-manager
  - serverless-offline

package:
  excludeDevDependencies: true
  exclude:
    - .tests/**

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  environment:
    PRODUCTS_TABLE: ${self:service}-${sls:stage}-roastly-products
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

functions: ${file(serverless-dynamic.js)}

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  customDomain:
    domainName: roastly-js-serverless.projects.lauraesteves.com
    basePath: ''
    stage: prod
    certificateArn: arn:aws:acm:us-east-1:958586644302:certificate/0a94af1b-caf3-4b54-9c62-e92f472899dd
    createRoute53Record: true
    createRoute53IPv6Record: true
    hostedZoneId: Z05144853OREESLU099I6
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  serverless-offline:
    environment:
      IS_OFFLINE: true
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy